services:
  postgres-db:
    image: postgres:17-alpine
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    networks:
      - project

  migrate:
    image: migrate/migrate
    depends_on:
      - postgres-db
    volumes:
      - ./schema:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:qwerty@postgres-db:5432/postgres?sslmode=disable",
      "up"
    ]
    networks:
      - project

  postgres-adminer:
    image: dpage/pgadmin4
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres-db
    networks:
      - project

  server:
    build:
      context: .
      dockerfile: docker-files/server.go.dockerfile
      args:
        MODULE_PATH: ${SERVER_MODULE_PATH}
        SERVICE_PATH: ${SERVER_SERVICE_PATH}
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - postgres-db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      TZ: ${TZ}
    networks:
      - project

networks:
  project:
    driver: bridge

volumes:
  pgdata:
  pgadmin: